import { Outfit } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Blogg App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await getServerSession(authOptions);
  console.log(data);
  return (
    <html lang="en">
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
